apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
stringData:
  # Define keys and references to AWS Secrets Manager
  DB_USERNAME: "{{resolve:secretsmanager:my-db-secret:SecretString:username}}"
  DB_PASSWORD: "{{resolve:secretsmanager:my-db-secret:SecretString:password}}"
  API_KEY: "{{resolve:secretsmanager:my-api-key:SecretString:apikey}}"
