apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8090
          protocol: TCP
      volumeMounts: 
        - name: nginx-data
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nginx-data
      persistentVolumeClaim:
        claimName: nginx-pvc



