apiVersion: v1
kind: Pod
metadata:
  name: nginix-pd-demo
  labels:
    app: nginix01
    env: dev01
spec:
  containers:
  - name: demo-container
    image: nginx:latest
    ports:
    - name: container-port
      containerPort: 80
      protocol: TCP
 