apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysqldb
    type: mysql
    env: prod
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      name: mysql-demo
      labels:
        app: mysqldb
        type: mysql
        env: prod
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        envFrom:
          - configMapRef:
              name: my-config-envfrom
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/mysql
      volumes:
      - name: shared-data
        emptyDir: {}




      

