apiVersion: apps/v1
kind: Deployment
metadata:
  name: testereplicadata
  labels:
    app: nginx
    env: uat
spec:
  replicas: 4
  selector:
    matchLabels:
      version: "3"
      app: pointing-it
  template:
    metadata:
      labels:
        app: pointing-it
        version: "3"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  # Corrected field name
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: NotIn
                values:
                - dev-master
                - prod-worker
      containers:
        - name: testcont
          image: nginx:1.23.0
          ports:
            - containerPort: 80
