apiVersion: v1
kind: Pod
metadata:
  name: nginix-pd-demo
  labels:
    app: nginix
    env: dev
  namespace: mathins
spec:
  # serviceAccountName: mathi-sa-acc
  containers:
  - name: demo-container
    image: nginx:latest
    ports:
    - name: container-port
      containerPort: 80
      protocol: TCP
 
  
