# example-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mathi-sa-acc
  namespace: mathins
# autoMountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mathins
  name: example-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-rolebinding
  namespace: mathins
subjects:
- kind: ServiceAccount
  name: mathi-sa-acc
  namespace: mathins
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io
