apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd  # Specify the desired namespace for the Argo CD Application
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  project: default
  source:
    repoURL: 'https://github.com/mathi686/k8manifest.git'
    path: 'deployement'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - '--sync-interval=5s'