apiVersion: v1
kind: Pod
metadata:
  name: testpod-dockersec
spec:
  imagePullSecrets:
    - name: centos8-sec
  containers:
   - name: centos
     image: ookeymathi/centos8:1.1
     imagePullPolicy: Always