# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginix-pd-demo
#   labels:
#     app: nginix
#     env: dev
# spec:
#   # affinity:
#   #   nodeAffinity:
#   #     requiredDuringSchedulingIgnoredDuringExecution:  # Corrected field name
#   #       nodeSelectorTerms:
#   #       - matchExpressions:
#   #         - key: env
#   #           operator: In
#   #           values:
#   #           - dev-master
#   tolerations:
#   - key: "type"
#     operator: Equal
#     value: master
#     effect: NoSchdule
#   containers:
#   - name: demo-container
#     image: nginx:latest
#     ports:
#     - name: container-port
#       containerPort: 80
#       protocol: TCP  
apiVersion: v1
kind: Pod
metadata:
  name: nginix-pd-demo
  labels:
    app: nginix
    env: dev
spec:
  tolerations:
  - key: type
    operator: Equal
    value: master
    effect: NoSchedule
  containers:
  - name: demo-container
    image: nginx:latest
    ports:
    - name: container-port
      containerPort: 80
      protocol: TCP
