apiVersion: v1
kind: Pod
metadata:
  name: testpod-sec
spec:
  containers:
  -  name: alpine
     image: alpine:latest
     command:
     - ls
     - "-l"
     - "var/tmp"
     volumeMounts:
       - name: db-files
         mountPath: "var/tmp"
  volumes:
    - name: db-files
      secret:
        secretName: my-sec
  restartPolicy: Never
